### ISSUE TITLE
emcc errors when making RetroArch dist-cores

### ISSUE THREAD

**Issue by TheRealVira** [EmulatorJS/RetroArch#11]
## Description

I have followed the guide over on https://emulatorjs.org/docs/building.html, but got stuck during the WASM build process.

### Expected behavior

```
emmake ./dist-cores.sh emscripten
```

This should build the WASM files. Before that I have built https://github.com/libretro/libretro-fceumm into `fceumm_libretro_emscripten.bc`.

### Actual behavior

```
root@retro:~/RetroArch/dist-scripts# emmake ./dist-cores.sh emscripten
make: ./dist-cores.sh emscripten
make: Entering directory '/root/RetroArch'
rm -rf obj-emscripten
rm -f retroarch.js
make: Leaving directory '/root/RetroArch'
Buildbot: building for emscripten
-- Building core: fceumm --
NAME: fceumm
ASYNC: 0
PTHREAD: 0
LTO: 0
WASM: 1
GLES3: 0
STACK_MEMORY: 8388608
HEAP_MEMORY: 268435456
BUILD COMMAND: make -C ../ -f Makefile.emscripten  PTHREAD=0 ASYNC=0 WASM=1  LTO=0 HAVE_OPENGLES3=0 STACK_MEMORY=8388608 HEAP_MEMORY=268435456 -j7 TARGET=fceumm_libretro.js
make: Entering directory '/root/RetroArch'
CC version_git.c
CC frontend/frontend_driver.c
CC retroarch.c
CC runloop.c
emcc: error: setting `EXPORTED_FUNCTIONS` expects `<class 'list'>` but got `<class 'str'>`
make: *** [Makefile.emscripten:196: obj-emscripten/version_git.o] Error 1
make: *** Waiting for unfinished jobs....
CC driver.c
emcc: error: setting `EXPORTED_FUNCTIONS` expects `<class 'list'>` but got `<class 'str'>`
make: *** [Makefile.emscripten:197: obj-emscripten/frontend/frontend_driver.o] Error 1
emcc: error: setting `EXPORTED_FUNCTIONS` expects `<class 'list'>` but got `<class 'str'>`
make: *** [Makefile.emscripten:197: obj-emscripten/retroarch.o] Error 1
emcc: error: setting `EXPORTED_FUNCTIONS` expects `<class 'list'>` but got `<class 'str'>`
make: *** [Makefile.emscripten:197: obj-emscripten/runloop.o] Error 1
emcc: error: setting `EXPORTED_FUNCTIONS` expects `<class 'list'>` but got `<class 'str'>`
make: *** [Makefile.emscripten:197: obj-emscripten/driver.o] Error 1
make: Leaving directory '/root/RetroArch'
```

### Steps to reproduce the bug

1. `git clone https://github.com/libretro/libretro-fceumm.git`
2. `cd libretro-fceumm/`
3. `emmake make -f Makefile.libretro platform=emscripten`
4. `cd ..`
5. `git clone https://github.com/ethanaobrien/RetroArch.git`
6. `cp libretro-fceumm/fceumm_libretro_emscripten.bc RetroArch/dist-scripts/fceumm_libretro_emscripten.bc`
7. `cd RetroArch/dist-scripts`
8. `emmake ./dist-cores.sh emscripten`

### Version/Commit

- RetroArch: Master

### Environment information

- OS: `Debian GNU/Linux 11`
- Compiler:

```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 2.0.12
Debian clang version 11.0.1-2
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: /bin
```

**Comment by ethanaobrien** [comment]
Can you try cloning `https://github.com/EmulatorJS/RetroArch.git` instead of `https://github.com/ethanaobrien/RetroArch.git`? I moved this to an organization however long ago and might have missed that. I'll get that changed in the docs
